# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:2.3.5

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
